# Generated by Django 5.2 on 2025-04-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('CourseNumber', models.IntegerField()),
                ('InstructorName', models.CharField(max_length=200)),
                ('Duration', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'UniversityClasses',
            },
        ),
    ]
