Python 3.12.6 (tags/v3.12.6:a4a2d2b, Sep  6 2024, 20:11:23) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> import sqlite3  
... 
... 
... connection = sqlite3.connect("C:/Users/mirko/OneDrive/Desktop/Python 2/test_database.db")
... 
... c = connection.cursor()
... 
... c.execute("CREATE TABLE People(FirstName TEXT, LastName TEXT, Age INT)")
... 
... c.execute("INSERT INTO People VALUES('Ron', 'Obvious', '42')")
... 
... connection.commit()
... connection.close()
... 
... 
